# Generated by Django 5.2.7 on 2025-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_address_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Ảnh người dùng', 'verbose_name_plural': 'Ảnh người dùng'},
        ),
    ]
