# Generated by Django 5.2.7 on 2025-11-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={},
        ),
    ]
